# Generated by Django 3.0.4 on 2020-03-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
